#!/usr/bin/env bash

readonly DOTFILES=${DOTFILES:-"${HOME}/dotfiles"}
# readonly DOTFILES_REPO=${DOTFILES_REPO:-"${HOME}/dotfiles"}
readonly repo="https://github.com/shawnohare/dotfiles.git"

cd "${HOME}"
if [ ! -d "${DOTFILES}" ]; then
  echo "Cloning ${repo}" 
  git clone --recursive "${repo}" "${DOTFILES}"
fi


# TODO: do not make the hard lin to linux debian.  Instead,
# try to install as much as possible via nix-env.
if [ -d "${DOTFILES}" ]; then
  "${DOTFILES}/bin/bin/dotfiles" -v install linux debian
else
  echo "Error: Could not clone dotfiles ${repo} into ${DOTFILES}."
  exit 1
fi
