#!/usr/bin/env bash

readonly DOTFILES=${DOTFILES:-"${HOME}/dotfiles"}
readonly repo="https://github.com/shawnohare/dotfiles.git"

cd "${HOME}"
if [ ! -d "${DOTFILES}" ]; then
  echo "Cloning ${repo}" 
  git clone --recursive "${repo}" "${DOTFILES}"
fi


if [ -d "${DOTFILES}" ]; then
  "${DOTFILES}/bin/bin/dotfiles" -v 2 install 
else
  echo "Error: Could not clone dotfiles ${repo} into ${DOTFILES}."
  exit 1
fi

exit 0
