" Before setting any VIM-only options, enable full VIM features
set nocompatible  " make VIM iMproved rather than legacy compatible
" map esc to jk in insert mode, don't interpret the map
inoremap jk <Esc>
" ===== Colors =====
syntax on  " turn on syntax highlighting
set cursorline  " highlight current line
colorscheme slate 
" ===== General =====
set number " show line numbers
set backspace=indent,eol,start " allow backspaces in insert mode
set history=1000  " store lots of :cmdline history
"set showcmd  " show incomplete commands at bottom
"set showmode " show current mode at bottom
set visualbell  " disable audible bell
set autoread  " reload files changed outside vim
" ===== Indentation =====
set smarttab " <Tab> interpretation depends on cursor and siftwidth, tabstop, softtabstop
set tabstop=2  " number of visual spaces per <Tab> character
set expandtab  " <Tab> converted to softtabstop # spaces
set softtabstop=2 " number of spaces <Tab> converted to
set shiftwidth=2 " <Tab> converts to this # spaces at beginning of line
set smartindent
set autoindent
" =====  Completion =====
set wildmenu  " visual autocomplete for comand menu
" ===== Folding =====
set foldmethod=indent  " fold based on indent
set foldnestmax=3  " deepest fold level
set nofoldenable  " don't fold by default 
" ===== Status line =====
set laststatus=2
set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'} "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file
